import type { Plant, PlantCategory } from "@/lib/banquet-party/types";

export const PLANT_CATEGORY_ORDER: PlantCategory[] = [
  "white",
  "pink",
  "red",
  "purple",
  "yellow",
  "orange",
  "green",
  "neutral",
  "dark",
];

export const PLANTS: Plant[] = [
  // white
  {
    id: "veronicastrum_album",
    name: "白花腹水草",
    nameEn: "Veronicastrum album 'Album'",
    colorName: "纯白",
    hex: "#F5F3F0",
    role: "primary",
    category: "white",
  },
  {
    id: "echinacea_pallida",
    name: "苍白松果菊",
    nameEn: "Echinacea pallida",
    colorName: "象牙白",
    hex: "#F0EDE5",
    role: "primary",
    category: "white",
  },
  {
    id: "briza_maxima",
    name: "大凌风草",
    nameEn: "Briza maxima",
    colorName: "银白",
    hex: "#E8E5DF",
    role: "secondary",
    category: "white",
  },
  {
    id: "aquilegia_alba",
    name: "白花耧斗菜",
    nameEn: "Aquilegia vulgaris 'Alba'",
    colorName: "乳白",
    hex: "#F5F0E8",
    role: "secondary",
    category: "white",
  },
  // pink
  {
    id: "achillea_filipendulina",
    name: "凤尾蓍",
    nameEn: "Achillea filipendulina",
    colorName: "柔粉",
    hex: "#F0D5D0",
    role: "primary",
    category: "pink",
  },
  {
    id: "verbena_bonariensis",
    name: "柳叶马鞭草",
    nameEn: "Verbena bonariensis",
    colorName: "淡紫粉",
    hex: "#D4C0D0",
    role: "primary",
    category: "pink",
  },
  {
    id: "cortaderia_pumila",
    name: "矮蒲苇",
    nameEn: "Cortaderia selloana 'Pumila'",
    colorName: "暖粉",
    hex: "#E8C8B8",
    role: "secondary",
    category: "pink",
  },
  {
    id: "lycoris_radiata",
    name: "红花石蒜",
    nameEn: "Lycoris radiata",
    colorName: "绯粉",
    hex: "#E85D75",
    role: "accent",
    category: "pink",
  },
  // red
  {
    id: "papaver_rhoeas",
    name: "罂粟花",
    nameEn: "Papaver rhoeas",
    colorName: "朱红",
    hex: "#E03C31",
    role: "accent",
    category: "red",
  },
  {
    id: "lychnis_coronaria",
    name: "大花剪秋萝",
    nameEn: "Lychnis coronaria",
    colorName: "绯红",
    hex: "#C41E3A",
    role: "accent",
    category: "red",
  },
  {
    id: "liatris_spicata",
    name: "蛇鞭菊",
    nameEn: "Liatris spicata",
    colorName: "紫红",
    hex: "#B2226B",
    role: "secondary",
    category: "red",
  },
  {
    id: "kniphofia_uvaria",
    name: "火炬花",
    nameEn: "Kniphofia uvaria",
    colorName: "橙红",
    hex: "#E86A33",
    role: "accent",
    category: "red",
  },
  // purple
  {
    id: "scabiosa",
    name: "蓝盆花",
    nameEn: "Scabiosa",
    colorName: "蓝紫",
    hex: "#7B8DB8",
    role: "primary",
    category: "purple",
  },
  {
    id: "aster_twilight",
    name: "紫菀",
    nameEn: "Aster 'Twilight'",
    colorName: "暮色紫",
    hex: "#8B6B8B",
    role: "primary",
    category: "purple",
  },
  {
    id: "echinops",
    name: "蓝刺头",
    nameEn: "Echinops",
    colorName: "钢蓝",
    hex: "#6B8B9B",
    role: "secondary",
    category: "purple",
  },
  {
    id: "salvia_uliginosa",
    name: "天青鼠尾草",
    nameEn: "Salvia uliginosa",
    colorName: "天蓝",
    hex: "#8BB8D4",
    role: "secondary",
    category: "purple",
  },
  // yellow
  {
    id: "rudbeckia",
    name: "金光菊",
    nameEn: "Rudbeckia",
    colorName: "金盏黄",
    hex: "#E8A853",
    role: "primary",
    category: "yellow",
  },
  {
    id: "helenium",
    name: "堆心菊",
    nameEn: "Helenium",
    colorName: "暖金",
    hex: "#D4A030",
    role: "primary",
    category: "yellow",
  },
  {
    id: "coreopsis_verticillata",
    name: "轮叶金鸡菊",
    nameEn: "Coreopsis verticillata",
    colorName: "淡金",
    hex: "#E8C84A",
    role: "secondary",
    category: "yellow",
  },
  // orange
  {
    id: "solidago_goldenmosa",
    name: "加拿大一枝黄花",
    nameEn: "Solidago 'Goldenmosa'",
    colorName: "金橙",
    hex: "#D4883A",
    role: "primary",
    category: "orange",
  },
  {
    id: "aquilegia_orange",
    name: "橙花耧斗菜",
    nameEn: "Aquilegia vulgaris 'Orange'",
    colorName: "暖橙",
    hex: "#E87A3A",
    role: "secondary",
    category: "orange",
  },
  // green
  {
    id: "thalictrum",
    name: "唐松草",
    nameEn: "Thalictrum",
    colorName: "嫩绿",
    hex: "#8BB88B",
    role: "base",
    category: "green",
  },
  {
    id: "aruncus",
    name: "假升麻",
    nameEn: "Aruncus",
    colorName: "翠绿",
    hex: "#6B9B6B",
    role: "base",
    category: "green",
  },
  {
    id: "miscanthus_sinensis",
    name: "细叶芒",
    nameEn: "Miscanthus sinensis",
    colorName: "深绿",
    hex: "#5B7B5B",
    role: "base",
    category: "green",
  },
  {
    id: "nassella_tenuissima",
    name: "墨西哥羽毛草",
    nameEn: "Nassella tenuissima",
    colorName: "雾绿",
    hex: "#B8C8A8",
    role: "secondary",
    category: "green",
  },
  // neutral
  {
    id: "pennisetum",
    name: "狼尾草",
    nameEn: "Pennisetum",
    colorName: "暖棕",
    hex: "#B8886B",
    role: "base",
    category: "neutral",
  },
  {
    id: "sanguisorba",
    name: "地榆",
    nameEn: "Sanguisorba",
    colorName: "红褐",
    hex: "#8B5A4A",
    role: "secondary",
    category: "neutral",
  },
  {
    id: "amorpha_canescens",
    name: "灰毛紫穗槐",
    nameEn: "Amorpha canescens",
    colorName: "灰紫",
    hex: "#9B8B9B",
    role: "secondary",
    category: "neutral",
  },
  {
    id: "jacobaea_maritima",
    name: "银叶菊",
    nameEn: "Jacobaea maritima",
    colorName: "烟灰",
    hex: "#C8C0B8",
    role: "base",
    category: "neutral",
  },
  // dark
  {
    id: "prunus_nigra",
    name: "紫叶稠李",
    nameEn: "Prunus cerasifera 'Nigra'",
    colorName: "紫黑",
    hex: "#3D1F2E",
    role: "accent",
    category: "dark",
  },
  {
    id: "aquilegia_atrata",
    name: "深紫耧斗菜",
    nameEn: "Aquilegia atrata",
    colorName: "紫褐",
    hex: "#4A2A3A",
    role: "base",
    category: "dark",
  },
  {
    id: "aster_dark_beauty",
    name: "暗红紫菀",
    nameEn: "Aster 'Dark Beauty'",
    colorName: "暗红褐",
    hex: "#5C2E2E",
    role: "base",
    category: "dark",
  },
];

const plantMap = new Map(PLANTS.map((p) => [p.id, p]));

export function getPlant(id: string): Plant | undefined {
  return plantMap.get(id);
}

export function getPlantsByCategory(category: PlantCategory): Plant[] {
  return PLANTS.filter((p) => p.category === category);
}
